{
 "title": "XLayer",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Successful Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_tx_count{instance=\"xlayer-seq:9095\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sequencer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transaction Per Second",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "tx/s" } },
   "targets": [
    {
     "expr": "rate(sequencer_tx_count{instance=\"xlayer-seq:9095\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hierarchical Timing Dashboard",
   "type": "timeseries",
   "description": "Hierarchical view of processing times for batch operations",
   "gridPos": { "h": 12, "w": 12, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sequencer_batch_duration{instance=\"$instance\"}",
     "legendFormat": "Total Batch Duration"
    },
    {
     "expr": "sequencer_sequencing_batch_timing{instance=\"$instance\"}",
     "legendFormat": "Sequencing Batch Timing"
    },
    {
     "expr": "sequencer_process_tx_timing{instance=\"$instance\"}",
     "legendFormat": "Process Tx Timing"
    },
    {
     "expr": "sequencer_zk_inc_intermediate_hashes_timing{instance=\"$instance\"}",
     "legendFormat": "ZK Inc Intermediate Hashes"
    },
    {
     "expr": "sequencer_batch_commit_db_timing{instance=\"$instance\"}",
     "legendFormat": "Batch Commit DB"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "Transaction Processing Hierarchy",
   "type": "timeseries",
   "description": "Transaction Processing Detail",
   "gridPos": { "h": 10, "w": 12, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sequencer_process_tx_timing{instance=\"$instance\"}",
     "legendFormat": "Process Tx (Total)"
    },
    {
     "expr": "sequencer_get_tx_timing{instance=\"$instance\"}",
     "legendFormat": "Get Tx Timing"
    },
    {
     "expr": "sequencer_get_tx_pause_timing{instance=\"xlayer-seq:9095\"}",
     "legendFormat": "Get Tx Pause Timing"
    }
   ]
  },
  {
   "title": "Block Gas Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "sequencer_block_gas_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  { "title": "Sequencer Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Dynamic Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "GWei" } },
   "targets": [
    {
     "expr": "rpc_dynamic_gas_price{instance=\"xlayer-seq:9095\"}/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inner Transaction Executed",
   "type": "timeseries",
   "description": "Trace contract calls on OKLink\nExample: \nhttps://www.oklink.com/zh-hans/xlayer/tx/0x60d98f5b2ef33de2d1697bd57ee4b3f1ff0ce86aca2adc528ca647add430f173/internal",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "rpc_inner_tx_executed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process Time Distribution",
   "type": "piechart",
   "description": "Percentage of time spent in each processing stage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sequencer_process_tx_timing / sequencer_batch_duration * 100",
     "legendFormat": "Process Tx"
    },
    {
     "expr": "sequencer_pb_state_timing / sequencer_batch_duration * 100",
     "legendFormat": "PB State"
    },
    {
     "expr": "sequencer_zk_inc_intermediate_hashes_timing / sequencer_batch_duration * 100",
     "legendFormat": "ZK Inc Intermediate Hashes"
    },
    {
     "expr": "sequencer_finalise_block_write_timing / sequencer_batch_duration * 100",
     "legendFormat": "Finalise Block Write"
    },
    {
     "expr": "sequencer_batch_commit_db_timing / sequencer_batch_duration * 100",
     "legendFormat": "Batch Commit DB"
    }
   ]
  },
  {
   "title": "Processing Time Breakdown",
   "type": "barchart",
   "description": "Historical view of processing time by stage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "sequencer_process_tx_timing", "legendFormat": "Process Tx" },
    { "expr": "sequencer_pb_state_timing", "legendFormat": "PB State" },
    {
     "expr": "sequencer_zk_inc_intermediate_hashes_timing",
     "legendFormat": "ZK Inc Hashes"
    },
    {
     "expr": "sequencer_finalise_block_write_timing",
     "legendFormat": "Finalise Block"
    },
    {
     "expr": "sequencer_batch_commit_db_timing",
     "legendFormat": "Commit DB"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\",stage=\"headers\"}",
     "legendFormat": "header: {{instance}}"
    },
    {
     "expr": "chain_head_block{instance=~\"$instance\"}",
     "legendFormat": "block: {{instance}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{instance=~\"$instance\"}",
     "legendFormat": "executable: {{instance}}"
    },
    {
     "expr": "txpool_basefee{instance=~\"$instance\"}",
     "legendFormat": "basefee: {{instance}}"
    },
    {
     "expr": "txpool_queued{instance=~\"$instance\"}",
     "legendFormat": "gapped: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "current: {{ instance }}"
    }
   ]
  },
  {
   "title": "Sync Stages progress",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 10, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sync{instance=~\"$instance\"}",
     "legendFormat": "{{ stage }}: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  }
 ]
}